baseURL = "https://markurusov1.github.io/defischolar_site/"
languageCode = "en-us"
title = "DeFi Scholar: High Schooler’s Guide to Decentralized Finance"

enableGitInfo = true
publishDir = "docs"

[module]
[[module.imports]]
path = "github.com/gethinode/hinode"

[params]
description = "Learn DeFi together—by high schoolers, for high schoolers."
darkModeToggle = true  # Easy site-wide theme switcher