# baseURL = 'https://markurusov1.github.io/defischolar_site/'
languageCode = 'en-us'
title = 'DeFi Scholar'

canonifyURLs = true
relativeURLs = false

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'
[[module.imports]]
path = 'github.com/hugomods/icons/vendors/lucide'

[params]
# Options: "light" (always light), "dark" (always dark), "auto" (follow system â€“ default)
BookTheme = "auto"
BookSearch = true

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true