baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

[params]
# Options: "light" (always light), "dark" (always dark), "auto" (follow system â€“ default)
BookTheme = "auto"
customCSS = ["css/custom.css"]

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true